---
title: "Lesson 4B: Continuous Distributions"
subtitle: "The Normal Distribution"
author: "Gabriel Odom, Kazi Tanvir Hasan, and Ning Sun"
date: "2022-10-05"
format: html
---


# Introduction

The Normal Distribution, denoted by $\text{N}(\mu, \sigma^2)$ has PDF 
$f(x|\mu, \sigma^2) \equiv \frac{1}{\sigma \sqrt{2\pi}}e^{-\frac{1}{2\sigma^2}(x-\mu)^2}$  for $\mu \in (-\infty, \infty)$, $\sigma^2 \in (-0, \infty)$ and $x \in \mathbb{R}$.


# First Moment

\begin{align*}
E[X] &= \int_{-\infty}^{\infty} x \frac{1}{\sigma \sqrt{2\pi}}e^{-\frac{1}{2\sigma^2}(x-\mu)^2} dx\\
&= \frac{1}{\sigma \sqrt{2\pi}} 
\int_{-\infty}^{\infty} x e^{-\frac{1}{2\sigma^2}(x-\mu)^2} dx\\
\end{align*}

Let, 
\begin{align*}
z &= \frac{x-\mu}{\sigma} \\ 
\implies x &= \sigma z + \mu \\ 
\implies dx = \sigma dz
\end{align*}

\begin{align*}
\therefore E[X] &= \frac{1}{\sigma \sqrt{2\pi}} \int_{-\infty}^{\infty} (\sigma z + \mu)e^{-\frac{\sigma z + \mu - \mu}{2\sigma^2}} dz\\
&= \frac{1}{\sqrt{2\pi}} \int_{-\infty}^{\infty} (\sigma z + \mu) e^{-\frac{z^2}{2}}dz\\
&= \frac{1}{\sqrt{2\pi}}\left [\int_{-\infty}^{\infty} \sigma z e^{-\frac{z^2}{2}} + \int_{-\infty}^{\infty} \mu z e^{-\frac{z^2}{2}}dz \right]
\end{align*}

Now, $\int_{-\infty}^{\infty} z e^{-\frac{z^2}{2}} dz= 0; \quad$ 
Since, this is an odd function.

and, $\int_{-\infty}^{\infty} e^{-\frac{z^2}{2}} dz= 2\int_{0}^{\infty} e^{-\frac{z^2}{2}}dz; \quad$ Since, this is an even function.

So, \begin{align*}
E[X] &= \frac{\mu}{\sqrt 2\pi}2 \int_{0}^{\infty} e^{-\frac{z^2}{2}}dz\\
&= \frac{\mu}{\sqrt \pi} \sqrt \pi; \quad[\text{Since,} \int_{0}^{\infty} e^{-\frac{x^2}{2}}dx = \sqrt \pi]\\
\therefore E[X] &= \mu
\end{align*}


# Second Moment and Variance

\begin{align*}
Var[X] &= \int_{-\infty}^{\infty} (x-\mu)^2 \frac{1}{\sigma \sqrt{2\pi}}e^{-\frac{1}{2\sigma^2}(x-\mu)^2} dx\\
&= \frac{1}{\sigma \sqrt{2\pi}} 
\int_{-\infty}^{\infty} (x-\mu)^2 e^{-\frac{1}{2\sigma^2}(x-\mu)^2}dx \\
\end{align*}

Let, 
\begin{align*}
z &= \frac{x-\mu}{\sigma} \\ 
\implies x &= \sigma z + \mu \\ 
\implies dx = \sigma dz
\end{align*}

\begin{align*}
\therefore Var[X] &= \frac{1}{\sigma \sqrt{2\pi}} \int_{-\infty}^{\infty} (\sigma z)^2 e^{-\frac{\sigma z + \mu - \mu}{2\sigma^2}}dz\\
&= \frac{\sigma^2}{\sqrt{2\pi}} \int_{-\infty}^{\infty}  z^2  e^{-\frac{z^2}{2}}dz\\
&= \frac{\sigma^2}{\sqrt{2\pi}} 2\int_{0}^{\infty}  z^2  e^{-\frac{z^2}{2}}dz;
\quad \text{Since, this is an even function}\\
\end{align*}

Again, let-
\begin{align*}
z^2/2 &= t \\ 
\implies z^2 &= 2t \\ 
\implies z &= \sqrt{2t} \\ 
\implies dz =  \frac{2dt}{2z} = \frac{dt}{\sqrt{2t}}
\end{align*}

Then,
\begin{align*}
\therefore Var[X] &= \frac{2\sigma^2}{\sqrt{2\pi}} \int_{0}^{\infty}  2t  e^{-t}\frac{dt}{\sqrt{2t}}\\
&= \frac{2\sigma^2}{\sqrt{\pi}} \int_{0}^{\infty} t^{1/2}  e^{-t} dt\\
&= \frac{2\sigma^2}{\sqrt{\pi}} \int_{0}^{\infty} e^{-t} t^{\frac{3}{2}-1} dt\\
&= \frac{2\sigma^2}{\sqrt{\pi}} \Gamma{\left(\frac{3}{2}\right)}; \quad \left[\text{Since,} \Gamma{(n)}=  \int_{0}^{\infty} e^{-x} x^{n-1} dx \right]\\
&= \frac{2\sigma^2}{\sqrt{\pi}} \frac{1}{2}\Gamma{\left(\frac{1}{2}\right)}\\
&= \frac{2\sigma^2}{\sqrt{\pi}} \frac{1}{2}\sqrt{\pi}\\
\therefore Var[X] &= \sigma^2
\end{align*}

Then, the second moment- 
$E[X^2]= Var[X] - {E[X]}^2 = \sigma^2 - \mu^2$

# Moment Generating Function

\begin{align*}
M_X{t} = E[e^{tx}] &= \int_{-\infty}^{\infty} e^{tx} \frac{1}{\sigma \sqrt{2\pi}}e^{-\frac{1}{2\sigma^2}(x-\mu)^2} dx\\
 &= \frac{1}{\sigma\sqrt{2\pi}}\int_{-\infty}^{\infty} e^{tx} e^{-\frac{1}{2\sigma^2}(x-\mu)^2} dx
\end{align*}

Let, 
\begin{align*}
z &= \frac{x-\mu}{\sigma} \\ 
\implies x &= \sigma z + \mu \\ 
\implies dx = \sigma dz
\end{align*}

Then,
\begin{align*}
M_X{t} &= \frac{1}{\sigma\sqrt{2\pi}}\int_{-\infty}^{\infty} e^{\mu + \sigma z}t e^{-\frac{z^2}{2}(x-\mu)^2} \sigma dz\\
&=\frac{e^{\mu t}}{\sqrt{2\pi}}\int_{-\infty}^{\infty} e^{\sigma zt} e^{-\frac{z^2}{2}(x-\mu)^2} \sigma dz\\
&=\frac{e^{\mu t}}{\sqrt{2\pi}}\int_{-\infty}^{\infty} e^{z^2-2\sigma zt} \sigma dz\\
&=\frac{e^{\mu t}}{\sqrt{2\pi}}\int_{-\infty}^{\infty} e^{\frac{1}{2}{(z-\sigma t)^2- \sigma^2 t^2}} \sigma dz\\
&=\frac{e^{\mu t}}{\sqrt{2\pi}} e^{\frac{\sigma^2t^2}{2}}\int_{-\infty}^{\infty} e^{\frac{1}{2}{(z-\sigma t)^2}} \sigma dz\\
&=e^{\mu t} e^{\frac{\sigma^2t^2}{2}}\int_{-\infty}^{\infty} \frac{1}{\sqrt{2\pi}} e^{\frac{1}{2}{(z-\sigma t)^2}} \sigma dz\\
\therefore M_X{t} &= e^{\mu t} e^{\frac{\sigma^2t^2}{2}}; \quad [\text{Since,} z \sim N(\sigma t, 1)]
\end{align*}


# Likelihood and Log-Likelihood Functions



# Maximum Likelihood Estimators


## Analytic Solution


## Numeric Solution



# Assignments

Replicate these steps for the Gamma Distribution, and derive the Inverse Gamma Distribution.
